---
- hosts: ansiblehost

  tasks:
    - name: create docker image
      command: docker build -t regapp:latest .
      args:
       chdir: /opt/docker

    - name: Create tag to push image to docekrhub
      command: docker tag regapp:latest shubzz/java_app_img:latest

    - name: Push the image to dockerhub
      command: docker push shubzz/java_app_img:latest
